---
- name: capture hosts for standard compliance policy
  hosts: all
  gather_facts: yes
#  remote_user: cloud-user
  tasks:

    - name: create standard policy host list
      template:
        src: templates/STD_host_file_template.j2
        dest: /home/runner/files/std_compliance_hosts
      delegate_to: localhost
        

#    - name: set file content variable
#      set_stats:
#        data:
#          file_contents: "{{ item }}"
#      with_file:
#        - "files/std_compliance_hosts"
#      delegate_to: localhost


