---
- name: run insights compliance scan
  hosts: all
  become: true
#  gather_facts: no

  tasks:
    - name: run insights compliance
      import_role:
        name: redhat.insights.compliance
        tasks_from: run
